### PR TITLE
update esLint

### PR DESCRIPTION
**Pull request by daviscrib**
Add useState and useEffect in playground
Add backCard

### CODE REVIEW

**Review by Moonlow31 — APPROVED** [review]
esta buenos

**Review by GorskiAnthony — APPROVED** [review]

**Comment by GorskiAnthony** [comment]
Plop problème eslint
```text
/home/runner/work/JS-RemoteFR-CrewDragon-P2-Team2/JS-RemoteFR-CrewDragon-P2-Team2/client/src/components/Playground.jsx
  5:1   error  Expected 1 empty line after import statement not followed by another import  import/newline-after-import
  7:16  error  'setShow' is assigned a value but never used                                 no-unused-vars
```

**Comment by GorskiAnthony** [comment]
@daviscrib :)

**Comment by GorskiAnthony** [comment]
# 🎊

**Pull request merged**
